sudo: false
language: python
env:
  - TOXENV=py27-django111-sqlite PYTHONPATH=$HOME/virtualenv/python2.7.14/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
  - TOXENV=py27-django111-mysql PYTHONPATH=$HOME/virtualenv/python2.7.14/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
  - TOXENV=py27-django111-postgres PYTHONPATH=$HOME/virtualenv/python2.7.14/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
  # Meta
  - TOXENV=project PYTHONPATH=$HOME/virtualenv/python2.7.14/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
cache:
  directories:
    - pootle/static/js/node_modules
    - pootle/assets
install:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then upgrade="--upgrade"; fi;
      pip install $upgrade
      -r requirements/base.txt
      -r requirements/travis.txt
      -e .
script:
  - tox -e $TOXENV
after_script:
  # logs might get truncated https://github.com/travis-ci/travis-ci/issues/6018
  - sleep 1
notifications:
  email:
    on_failure: always
    on_success: change
before_cache:
  # Force rebuilds by removing cache for 'master' builds
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then rm -rf pootle/static/js/node_modules/* pootle/assets/* pootle/assets/.webassets-cache;  fi
services:
  - redis-server
  - elasticsearch
